apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-manager
  namespace: dev
  labels:
    app: storage-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-manager
  template:
    metadata:
      labels:
        app: storage-manager
    spec:
      containers:
        - name: storage-manager
          image: siddik3241/test-apps:latest   # <-- এইটা build করা image
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"