apiVersion: v1
kind: Service
metadata:
  name: storage-manager-service
  namespace: dev
spec:
  selector:
    app: storage-manager
  type: NodePort
  ports:
    - port: 3000          # Pod exposes
      targetPort: 3000    # Container port
      nodePort: 31000     # Access via minikube ip:31000